name: 반도체 시그널 알림
on:
  schedule:
    - cron: '0 22 * * 1-5'
  workflow_dispatch:
jobs:
  send-signal:
    runs-on: ubuntu-latest
    steps:
      - run: curl "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.CHAT_ID }}&text=반도체+시그널+체크+07:00%0AHBM+둔화%0A엔비디아+가이던스%0ADRAM+가격%0ASMH+추세%0A외국인+수급"
